## Travis CI Integration
language: csharp
solution: NitroDebugger.sln

# Use the new Travis CI infrastructure
sudo: false

install:
  - nuget restore NitroDebugger.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild NitroDebugger.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe NitroDebugger.UnitTests/bin/Debug/NitroDebugger.UnitTests.dll
